### ISSUE TITLE
config file and checkpoint file matching problems

### ISSUE THREAD

**Issue by babyMonkey8** [mdv3101/CDeCNet#15]
Hello, I am using your open source code to identify the picture table。I'm using this config file(dcn/db_cascade_mask_rcnn_x101_fpn_dconv_c3-c5_1x_coco.py) and checkpoint file(tablebank_sota.pth)。But the runtime error is:TypeError: __init__() got an unexpected keyword argument 'roi_head'，I wonder if this is caused by a mismatch between the config file and the checkpoint file.

**Comment by madhav1ag** [comment]
Hi @babyMonkey8 ,
The checkpoint and config files are correct, as many people are using this code without any issue.
I would suggest to build the code on a new virtual environment and try using   `python setup.py develop` instead of `pip install -v -e .` 
If the error is still there, please provide a detailed report, so that we can help you properly. Make sure you are using the correct versions of mmcv and other dependencies.

**Comment by babyMonkey8** [comment]
thank you，I'll try
